-- DO THIS FIRST
-- Add Stat columns 
alter table method_online add(
LEVEL_OF_TRAINING            VARCHAR2(20 BYTE),
  MEDIA_SUBCATEGORY                  VARCHAR2(150 BYTE),
  MEDIA_EMPHASIZED_NOTE        VARCHAR2(50 BYTE),
  SAM_COMPLEXITY                   VARCHAR2(10 BYTE));
  
  alter table method_online_jn add(
LEVEL_OF_TRAINING            VARCHAR2(20 BYTE),
  MEDIA_SUBCATEGORY                  VARCHAR2(150 BYTE),
  MEDIA_EMPHASIZED_NOTE        VARCHAR2(50 BYTE),
  SAM_COMPLEXITY                   VARCHAR2(10 BYTE));
  
  alter table method_stg add(
LEVEL_OF_TRAINING            VARCHAR2(20 BYTE),
  MEDIA_SUBCATEGORY                  VARCHAR2(150 BYTE),
  MEDIA_EMPHASIZED_NOTE        VARCHAR2(50 BYTE),
    SAM_COMPLEXITY                   VARCHAR2(10 BYTE));

  alter table method_stg_jn add(
LEVEL_OF_TRAINING            VARCHAR2(20 BYTE),
  MEDIA_SUBCATEGORY                  VARCHAR2(150 BYTE),
  MEDIA_EMPHASIZED_NOTE        VARCHAR2(50 BYTE),
    SAM_COMPLEXITY                   VARCHAR2(10 BYTE));
  
 alter table method add(
LEVEL_OF_TRAINING            VARCHAR2(20 BYTE),
  MEDIA_SUBCATEGORY                  VARCHAR2(150 BYTE),
  MEDIA_EMPHASIZED_NOTE        VARCHAR2(50 BYTE),
    SAM_COMPLEXITY                   VARCHAR2(10 BYTE));
  
  
   alter table method_fact add(
LEVEL_OF_TRAINING            VARCHAR2(20 BYTE),
  MEDIA_SUBCATEGORY                  VARCHAR2(150 BYTE),
  MEDIA_EMPHASIZED_NOTE        VARCHAR2(50 BYTE)
  SAM_COMPLEXITY                   VARCHAR2(10 BYTE));


-- modify cols to fit with new rules
  
  alter table method_online MODIFY (
  MEDIA_NAME                  VARCHAR2(30 BYTE) NULL,
  METHOD_SUBCATEGORY_ID       NUMBER(11) NULL);

    
      alter table method_stg MODIFY (
  MEDIA_NAME                  VARCHAR2(30 BYTE)  NULL,
     METHOD_SUBCATEGORY_ID       NUMBER(11) NULL);
    
      alter table method MODIFY (
  MEDIA_NAME                  VARCHAR2(30 BYTE) NULL ,
     METHOD_SUBCATEGORY_ID       NUMBER(11) NULL);
  
-- create constraints to accommodate stat methods

ALTER TABLE METHOD_ONLINE ADD (
  CONSTRAINT METHOD_ONLINE_C01
 CHECK ((METHOD_TYPE_ID != 3 AND MEDIA_NAME IS NOT NULL)  OR METHOD_TYPE_ID = 3));
 
 ALTER TABLE METHOD_STG ADD (
  CONSTRAINT METHOD_STG_C01
 CHECK ((METHOD_TYPE_ID != 3 AND MEDIA_NAME IS NOT NULL)  OR METHOD_TYPE_ID = 3));
 
 ALTER TABLE METHOD ADD (
  CONSTRAINT METHOD_C01
 CHECK ((METHOD_TYPE_ID != 3 AND MEDIA_NAME IS NOT NULL)  OR METHOD_TYPE_ID = 3));
    

 
 ALTER TABLE METHOD_ONLINE ADD (
  CONSTRAINT METHOD_ONLINE_C03
 CHECK ((METHOD_TYPE_ID != 3 AND METHOD_SUBCATEGORY_ID IS NOT NULL)  OR METHOD_TYPE_ID = 3));
 
 ALTER TABLE METHOD_STG ADD (
  CONSTRAINT METHOD_STG_C03
 CHECK ((METHOD_TYPE_ID != 3 AND METHOD_SUBCATEGORY_ID IS NOT NULL)  OR METHOD_TYPE_ID = 3));
 
 ALTER TABLE METHOD ADD (
  CONSTRAINT METHOD_C03
 CHECK ((METHOD_TYPE_ID != 3 AND METHOD_SUBCATEGORY_ID IS NOT NULL)  OR METHOD_TYPE_ID = 3));
 
-- make METHOD_ONLINE and METHOD_STG consistent (done on widev and witest, NOT witrans)

alter table method_online modify(  
DL_NOTE                     VARCHAR2(2000 BYTE),
  INTERFERENCES               VARCHAR2(3000 BYTE),
  LAST_UPDATE_DATE            DATE,
  INSTRUMENTATION_ID          NUMBER(11)  ,
  SCREENING                   VARCHAR2(8 BYTE),  
  METHOD_DESCRIPTIVE_NAME     VARCHAR2(250 BYTE),
    METHOD_TYPE_ID              NUMBER    );
  

alter table method_online_jn modify(  
DL_NOTE                     VARCHAR2(2000 BYTE),
  INTERFERENCES               VARCHAR2(3000 BYTE),
  LAST_UPDATE_DATE            DATE,
  INSTRUMENTATION_ID          NUMBER(11)  ,
  SCREENING                   VARCHAR2(8 BYTE),  
  METHOD_DESCRIPTIVE_NAME     VARCHAR2(250 BYTE),
    METHOD_TYPE_ID              NUMBER    );
  

alter table method_online add(
CBR_ONLY                    VARCHAR2(1 BYTE)  DEFAULT 'N'                   NOT NULL,
  ETV_LINK                    VARCHAR2(120 BYTE),
  COLLECTED_SAMPLE_AMT_ML     VARCHAR2(10 BYTE),
  COLLECTED_SAMPLE_AMT_G      VARCHAR2(10 BYTE),
  LIQUID_SAMPLE_FLAG          VARCHAR2(1 BYTE),
  ANALYSIS_AMT_ML             VARCHAR2(10 BYTE),
  ANALYSIS_AMT_G              VARCHAR2(10 BYTE),
  PH_OF_ANALYTICAL_SAMPLE     VARCHAR2(10 BYTE),
  CALC_WASTE_AMT              NUMBER(7,2),
  QUALITY_REVIEW_ID           VARCHAR2(100 BYTE),
  PBT                         VARCHAR2(1 BYTE),
  TOXIC                       VARCHAR2(1 BYTE),
  CORROSIVE                   VARCHAR2(1 BYTE),
  WASTE                       VARCHAR2(1 BYTE),
  ASSUMPTIONS_COMMENTS        VARCHAR2(2000 BYTE),
  WQSA_CATEGORY_CD            NUMBER(11));
 
alter table method_online_jn add(
CBR_ONLY                    VARCHAR2(1 BYTE)  DEFAULT 'N'                   NOT NULL,
  ETV_LINK                    VARCHAR2(120 BYTE),
  COLLECTED_SAMPLE_AMT_ML     VARCHAR2(10 BYTE),
  COLLECTED_SAMPLE_AMT_G      VARCHAR2(10 BYTE),
  LIQUID_SAMPLE_FLAG          VARCHAR2(1 BYTE),
  ANALYSIS_AMT_ML             VARCHAR2(10 BYTE),
  ANALYSIS_AMT_G              VARCHAR2(10 BYTE),
  PH_OF_ANALYTICAL_SAMPLE     VARCHAR2(10 BYTE),
  CALC_WASTE_AMT              NUMBER(7,2),
  QUALITY_REVIEW_ID           VARCHAR2(100 BYTE),
  PBT                         VARCHAR2(1 BYTE),
  TOXIC                       VARCHAR2(1 BYTE),
  CORROSIVE                   VARCHAR2(1 BYTE),
  WASTE                       VARCHAR2(1 BYTE),
  ASSUMPTIONS_COMMENTS        VARCHAR2(2000 BYTE),
  WQSA_CATEGORY_CD            NUMBER(11)); 
  
alter table method_online  drop(
  TEST_SPECIES  );
 
alter table method_online_jn  drop(
  TEST_SPECIES  ); 
  
DROP TRIGGER  CG$ADS_METHOD_STG;
DROP TRIGGER  CG$AIS_METHOD_STG;
DROP TRIGGER  CG$AUS_METHOD_STG;
DROP TRIGGER  CG$BDR_METHOD_STG;
DROP TRIGGER  CG$BDS_METHOD_STG;
DROP TRIGGER  CG$BIR_METHOD_STG;
DROP TRIGGER  CG$BIS_METHOD_STG;
DROP TRIGGER  CG$BUR_METHOD_STG;
DROP TRIGGER  CG$BUS_METHOD_STG;
DROP TRIGGER  CG$ADS_METHOD_ONLINE;
DROP TRIGGER  CG$AIS_METHOD_ONLINE;
DROP TRIGGER  CG$AUS_METHOD_ONLINE;
DROP TRIGGER  CG$BDR_METHOD_ONLINE;
DROP TRIGGER  CG$BDS_METHOD_ONLINE;
DROP TRIGGER  CG$BIR_METHOD_ONLINE;
DROP TRIGGER  CG$BIS_METHOD_ONLINE;
DROP TRIGGER  CG$BUR_METHOD_ONLINE;
DROP TRIGGER  CG$BUS_METHOD_ONLINE;