-- do this second
SET DEFINE OFF;
/* Formatted on 7/20/2012 11:20:10 AM (QP5 v5.115.810.9015) */
CREATE OR REPLACE VIEW method_online_vw
(
    method_id,
    source_method_identifier,
    method_descriptive_name,
    method_official_name,
    method_source_id,
    source_citation_id,
    brief_method_summary,
    scope_and_application,
    media_name,
    approved,
    dl_type_id,
    dl_note,
    applicable_conc_range,
    conc_range_units,
    interferences,
    method_subcategory_id,
    matrix,
    qc_requirements,
    rapidity,
    waterbody_type,
    link_to_full_method,
    sample_handling,
    max_holding_time,
    sample_prep_methods,
    relative_cost_id,
    instrumentation_id,
    precision_descriptor_notes,
    insert_person_name,
    technique,
    method_source,
    method_source_name,
    method_source_contact,
    method_source_url,
    method_category,
    method_subcategory,
    dl_type,
    dl_type_description,
    source_citation_name,
    source_citation,
    source_citation_information,
    relative_cost_symbol,
    relative_cost,
    cost_effort_key,
    instrumentation,
    instrumentation_description
)
AS
    SELECT    mo.method_id,
                mo.source_method_identifier,
                mo.method_descriptive_name,
                mo.method_official_name,
                mo.method_source_id,
                mo.source_citation_id,
                mo.brief_method_summary,
                mo.scope_and_application,
                mo.media_name,
                mo.approved,
                mo.dl_type_id,
                mo.dl_note,
                mo.applicable_conc_range,
                mo.conc_range_units,
                mo.interferences,
                mo.method_subcategory_id,
                mo.matrix,
                mo.qc_requirements,
                mo.rapidity,
                mo.waterbody_type,
                mo.link_to_full_method,
                mo.sample_handling,
                mo.max_holding_time,
                mo.sample_prep_methods,
                mo.relative_cost_id,
                mo.instrumentation_id,
                mo.precision_descriptor_notes,
                mo.insert_person_name,
                mo.technique,
                s.method_source,
                s.method_source_name,
                s.method_source_contact,
                s.method_source_url,
                t.method_category,
                t.method_subcategory,
                u.dl_type,
                u.dl_type_description,
                v.source_citation_name,
                v.source_citation,
                v.source_citation_information,
                y.relative_cost_symbol,
                y.relative_cost,
                y.cost_effort_key,
                k.instrumentation,
                k.instrumentation_description
      FROM    method_online mo,
                method_source_ref s,
                method_subcategory_ref t,
                dl_ref u,
                source_citation_ref v,
                relative_cost_ref y,
                instrumentation_ref k
     WHERE         mo.method_source_id = s.method_source_id
                AND mo.instrumentation_id = k.instrumentation_id
                AND mo.method_subcategory_id = t.method_subcategory_id
                AND mo.dl_type_id = u.dl_type_id(+)
                AND mo.relative_cost_id = y.relative_cost_id(+)
                AND mo.source_citation_id = v.source_citation_id;


GRANT SELECT ON METHOD_ONLINE_VW TO NEMI_USER;


CREATE OR REPLACE VIEW method_vw
(
    method_id,
    source_method_identifier,
    method_descriptive_name,
    method_official_name,
    method_source_id,
    source_citation_id,
    brief_method_summary,
    scope_and_application,
    media_name,
    dl_type_id,
    dl_note,
    applicable_conc_range,
    conc_range_units,
    interferences,
    qc_requirements,
    cbr_only,
    link_to_full_method,
    sample_handling,
    max_holding_time,
    sample_prep_methods,
    relative_cost_id,
    instrumentation_id,
    precision_descriptor_notes,
    screening,
    rapidity,
    waterbody_type,
    matrix,
    method_source,
    method_source_name,
    method_source_contact,
    method_source_url,
    method_subcategory_id,
    method_category,
    method_subcategory,
    dl_type,
    dl_type_description,
    source_citation_name,
    source_citation,
    source_citation_information,
    relative_cost_symbol,
    relative_cost,
    cost_effort_key,
    instrumentation,
    instrumentation_description,
    regs_only,
    method_type_desc,
    method_type_id,
    date_loaded,
    collected_sample_amt_ml,
    collected_sample_amt_g,
    liquid_sample_flag,
    analysis_amt_ml,
    analysis_amt_g,
    ph_of_analytical_sample,
    calc_waste_amt,
    quality_review_id,
    pbt,
    toxic,
    corrosive,
    waste,
    assumptions_comments,
    smi_clean,
    level_of_training,
    media_subcategory,
    media_emphasized_note,
    sam_complexity
)
AS
    SELECT    m.method_id,
                m.source_method_identifier,
                m.method_descriptive_name,
                m.method_official_name,
                m.method_source_id,
                m.source_citation_id,
                m.brief_method_summary,
                m.scope_and_application,
                m.media_name,
                m.dl_type_id,
                m.dl_note,
                m.applicable_conc_range,
                m.conc_range_units,
                m.interferences,
                m.qc_requirements,
                m.cbr_only,
                m.link_to_full_method,
                m.sample_handling,
                m.max_holding_time,
                m.sample_prep_methods,
                m.relative_cost_id,
                m.instrumentation_id,
                m.precision_descriptor_notes,
                m.screening,
                m.rapidity,
                m.waterbody_type,
                m.matrix,
                s.method_source,
                s.method_source_name,
                s.method_source_contact,
                s.method_source_url,
                t.method_subcategory_id,
                t.method_category,
                t.method_subcategory,
                u.dl_type,
                u.dl_type_description,
                v.source_citation_name,
                v.source_citation,
                v.source_citation_information,
                y.relative_cost_symbol,
                y.relative_cost,
                y.cost_effort_key,
                k.instrumentation,
                k.instrumentation_description,
                m.regs_only,
                mt.method_type_desc,
                m.method_type_id,
                m.date_loaded,
                m.collected_sample_amt_ml,
                m.collected_sample_amt_g,
                m.liquid_sample_flag,
                m.analysis_amt_ml,
                m.analysis_amt_g,
                m.ph_of_analytical_sample,
                m.calc_waste_amt,
                m.quality_review_id,
                m.pbt,
                m.toxic,
                m.corrosive,
                m.waste,
                m.assumptions_comments,
                REPLACE (
                    REGEXP_REPLACE (
                        REGEXP_REPLACE (m.source_method_identifier,
                                             '((<su(b|p)>)|(</su(b|p)>))|\)',
                                             NULL
                                            ),
                        '[/!@#$%^&*]|( \()',
                        '-'
                    ),
                    ' ',
                    NULL
                )
                    smi_clean,
                m.level_of_training,
                m.media_subcategory,
                m.media_emphasized_note,
                m.sam_complexity
      FROM    method m,
                method_source_ref s,
                method_subcategory_ref t,
                dl_ref u,
                source_citation_ref v,
                relative_cost_ref y,
                instrumentation_ref k,
                method_type_ref mt
     WHERE         m.method_source_id = s.method_source_id
                AND m.instrumentation_id = k.instrumentation_id
                AND m.method_subcategory_id = t.method_subcategory_id(+)
                AND m.dl_type_id = u.dl_type_id(+)
                AND m.relative_cost_id = y.relative_cost_id(+)
                AND m.source_citation_id = v.source_citation_id
                AND m.cbr_only = 'N'
                AND m.approved = 'Y'
                AND m.method_type_id = mt.method_type_id(+);


GRANT SELECT ON METHOD_VW TO NEMI_USER;


CREATE OR REPLACE VIEW method_analyte_jn_online_vw
(
    dl_units,
    dl_value,
    analyte_method_id,
    precision,
    analyte_id,
    accuracy,
    accuracy_units,
    approved,
    precision_units,
    prec_acc_conc_used,
    false_positive_value,
    false_negative_value,
    analyte_code,
    analyte_name,
    preferred,
    analyte_type,
    dl_units_description,
    precision_units_description,
    accuracy_units_description,
    method_id,
    source_method_identifier,
    method_descriptive_name,
    method_official_name,
    method_source_id,
    source_citation_id,
    brief_method_summary,
    scope_and_application,
    media_name,
    dl_type_id,
    dl_note,
    applicable_conc_range,
    conc_range_units,
    interferences,
    rapidity,
    qc_requirements,
    instrumentation_id,
    instrumentation,
    instrumentation_description,
    precision_descriptor_notes,
    link_to_full_method,
    sample_handling,
    max_holding_time,
    sample_prep_methods,
    relative_cost_id,
    matrix,
    method_source,
    method_source_name,
    waterbody_type,
    method_source_url,
    technique,
    method_subcategory_id,
    method_category,
    method_subcategory,
    dl_type,
    dl_type_description,
    source_citation_name,
    source_citation,
    source_citation_information,
    relative_cost_symbol,
    relative_cost,
    cost_effort_key
)
AS
    SELECT    j.dl_units,
                j.dl_value,
                j.analyte_method_id,
                j.precision,
                j.analyte_id,
                j.accuracy,
                j.accuracy_units,
                mo_vw.approved,
                j.precision_units,
                j.prec_acc_conc_used,
                j.false_positive_value,
                j.false_negative_value,
                a_vw.analyte_code,
                a_vw.analyte_name,
                a_vw.preferred,
                a_vw.analyte_type,
                x.dl_units_description,
                y.precision_units_description,
                z.accuracy_units_description,
                mo_vw.method_id,
                mo_vw.source_method_identifier,
                mo_vw.method_descriptive_name,
                mo_vw.method_official_name,
                mo_vw.method_source_id,
                mo_vw.source_citation_id,
                mo_vw.brief_method_summary,
                mo_vw.scope_and_application,
                mo_vw.media_name,
                mo_vw.dl_type_id,
                mo_vw.dl_note,
                mo_vw.applicable_conc_range,
                mo_vw.conc_range_units,
                mo_vw.interferences,
                mo_vw.rapidity,
                mo_vw.qc_requirements,
                mo_vw.instrumentation_id,
                mo_vw.instrumentation,
                mo_vw.instrumentation_description,
                mo_vw.precision_descriptor_notes,
                mo_vw.link_to_full_method,
                mo_vw.sample_handling,
                mo_vw.max_holding_time,
                mo_vw.sample_prep_methods,
                mo_vw.relative_cost_id,
                mo_vw.matrix,
                mo_vw.method_source,
                mo_vw.method_source_name,
                mo_vw.waterbody_type,
                mo_vw.method_source_url,
                mo_vw.technique,
                mo_vw.method_subcategory_id,
                mo_vw.method_category,
                mo_vw.method_subcategory,
                mo_vw.dl_type,
                mo_vw.dl_type_description,
                mo_vw.source_citation_name,
                mo_vw.source_citation,
                mo_vw.source_citation_information,
                mo_vw.relative_cost_symbol,
                mo_vw.relative_cost,
                mo_vw.cost_effort_key
      FROM    method_online_vw mo_vw,
                analyte_method_jn_online j,
                instrumentation_ref k,
                dl_units_dom x,
                accuracy_units_dom z,
                precision_units_dom y,
                analyte_vw a_vw
     WHERE    j.method_id = mo_vw.method_id
                AND mo_vw.instrumentation_id = k.instrumentation_id
                AND (j.analyte_id = a_vw.analyte_id(+) AND a_vw.preferred(+) = -1)
                AND j.dl_units = x.dl_units(+)
                AND j.precision_units = y.precision_units(+)
                AND j.accuracy_units = z.accuracy_units(+);


GRANT SELECT ON METHOD_ANALYTE_JN_ONLINE_VW TO NEMI_USER;

CREATE OR REPLACE VIEW method_online_summary_vw
(
    revision_id,
    revision_information,
    revision_flag,
    mydoc,
    method_pdf,
    method_id,
    source_method_identifier,
    method_descriptive_name,
    method_official_name,
    method_source_id,
    source_citation_id,
    brief_method_summary,
    scope_and_application,
    media_name,
    dl_type_id,
    dl_note,
    applicable_conc_range,
    conc_range_units,
    interferences,
    method_source_contact,
    qc_requirements,
    link_to_full_method,
    sample_handling,
    max_holding_time,
    sample_prep_methods,
    relative_cost_id,
    method_source,
    method_source_name,
    method_source_url,
    precision_descriptor_notes,
    method_subcategory_id,
    method_category,
    method_subcategory,
    dl_type,
    dl_type_description,
    source_citation_name,
    source_citation,
    source_citation_information,
    relative_cost_symbol,
    relative_cost
)
AS
    SELECT    ro.revision_id,
                ro.revision_information,
                ro.revision_flag,
                mydoctype (ro.method_pdf, ro.mimetype) mydoc,
                ro.method_pdf,
                mo_vw.method_id,
                mo_vw.source_method_identifier,
                mo_vw.method_descriptive_name,
                mo_vw.method_official_name,
                mo_vw.method_source_id,
                mo_vw.source_citation_id,
                mo_vw.brief_method_summary,
                mo_vw.scope_and_application,
                mo_vw.media_name,
                mo_vw.dl_type_id,
                mo_vw.dl_note,
                mo_vw.applicable_conc_range,
                mo_vw.conc_range_units,
                mo_vw.interferences,
                mo_vw.method_source_contact,
                mo_vw.qc_requirements,
                mo_vw.link_to_full_method,
                mo_vw.sample_handling,
                mo_vw.max_holding_time,
                mo_vw.sample_prep_methods,
                mo_vw.relative_cost_id,
                mo_vw.method_source,
                mo_vw.method_source_name,
                mo_vw.method_source_url,
                mo_vw.precision_descriptor_notes,
                mo_vw.method_subcategory_id,
                mo_vw.method_category,
                mo_vw.method_subcategory,
                mo_vw.dl_type,
                mo_vw.dl_type_description,
                mo_vw.source_citation_name,
                mo_vw.source_citation,
                mo_vw.source_citation_information,
                mo_vw.relative_cost_symbol,
                mo_vw.relative_cost
      FROM    revision_join_online ro, method_online_vw mo_vw
     WHERE    ro.method_id = mo_vw.method_id AND ro.revision_flag = 1;


GRANT SELECT ON METHOD_ONLINE_SUMMARY_VW TO NEMI_USER;
