-- do this third

insert into method_online mo (
METHOD_ID         ,
  METHOD_SOURCE_ID       ,
  SOURCE_CITATION_ID     ,
  instrumentation_id,
  SOURCE_METHOD_IDENTIFIER ,
  METHOD_DESCRIPTIVE_NAME  ,
  METHOD_OFFICIAL_NAME     ,
  BRIEF_METHOD_SUMMARY ,
  LINK_TO_FULL_METHOD,
  METHOD_TYPE_ID,
  SAM_COMPLEXITY,
  MEDIA_SUBCATEGORY,
  LEVEL_OF_TRAINING,
  MEDIA_EMPHASIZED_NOTE,
  COMMENTS)
  SELECT
  METHOD_ID_SEQ.NEXTVAL,
  SC.SOURCE_ORGANIZATION_ID,
  SC.SOURCE_CITATION_ID,
  84,
  SC.SOURCE_CITATION,
  SC.SOURCE_CITATION,
  SC.TITLE,
  SC.ABSTRACT_SUMMARY,
  SC.LINK,
  3,
  SC.COMPLEXITY,
  SUBCATEGORY,
  LEVEL_OF_TRAINING,
  MEDIA_EMPHASIZED_NOTE,
  NOTES  
  FROM SOURCE_CITATION_REF SC
  WHERE CITATION_TYPE_ID = 2; 
  
  ALTER TABLE SOURCE_CITATION_REF_DESIGN57F3 RENAME COLUMN SOURCECITATIONREF_ID TO METHOD_ID;
  ALTER TABLE SOURCE_CITATION_REF_ANALYSD8D4 RENAME COLUMN SOURCECITATIONREF_ID TO METHOD_ID;
  ALTER TABLE SOURCE_CITATION_REF_MEDIA_1A7E RENAME COLUMN SOURCECITATIONREF_ID TO METHOD_ID;
  ALTER TABLE SOURCE_CITATION_REF_SPECIAEE02 RENAME COLUMN SOURCECITATIONREF_ID TO METHOD_ID;
  
  update SOURCE_CITATION_REF_DESIGN57F3 SC set METHOD_ID = (SELECT METHOD_ID FROM METHOD_ONLINE WHERE SOURCE_CITATION_ID = SC.METHOD_ID);
  update SOURCE_CITATION_REF_ANALYSD8D4 SC set METHOD_ID = (SELECT METHOD_ID FROM METHOD_ONLINE WHERE SOURCE_CITATION_ID = SC.METHOD_ID);
  update SOURCE_CITATION_REF_MEDIA_1A7E SC set METHOD_ID = (SELECT METHOD_ID FROM METHOD_ONLINE WHERE SOURCE_CITATION_ID = SC.METHOD_ID);
  update SOURCE_CITATION_REF_SPECIAEE02 SC set METHOD_ID = (SELECT METHOD_ID FROM METHOD_ONLINE WHERE SOURCE_CITATION_ID = SC.METHOD_ID);
  
  
ALTER TABLE SOURCE_CITATION_REF_DESIGN57F3 ADD (
  FOREIGN KEY (METHOD_ID) 
 REFERENCES METHOD_ONLINE (METHOD_ID)
    DEFERRABLE INITIALLY DEFERRED);
    
    
ALTER TABLE SOURCE_CITATION_REF_ANALYSD8D4 ADD (
  FOREIGN KEY (METHOD_ID) 
 REFERENCES METHOD_ONLINE (METHOD_ID)
    DEFERRABLE INITIALLY DEFERRED);
    
    
ALTER TABLE SOURCE_CITATION_REF_MEDIA_1A7E ADD (
  FOREIGN KEY (METHOD_ID) 
 REFERENCES METHOD_ONLINE (METHOD_ID)
    DEFERRABLE INITIALLY DEFERRED);
    
    
ALTER TABLE SOURCE_CITATION_REF_SPECIAEE02 ADD (
  FOREIGN KEY (METHOD_ID) 
 REFERENCES METHOD_ONLINE (METHOD_ID)
    DEFERRABLE INITIALLY DEFERRED);
