CREATE TABLE STAT_DESIGN_REL
(
  SOURCE_CITATION_ID  NUMBER,
  STAT_DESIGN_INDEX   NUMBER                    NOT NULL,
  DESIGN_PK           NUMBER                    NOT NULL,
  CONSTRAINT STAT_DESIGN_REL_PK
 PRIMARY KEY
 (DESIGN_PK),
  CONSTRAINT STAT_DESIGN_REL_R01 
 FOREIGN KEY (METHOD_ID) 
 REFERENCES METHOD (METHOD_ID),
  CONSTRAINT STAT_DESIGN_REL_R02 
 FOREIGN KEY (STAT_DESIGN_INDEX) 
 REFERENCES STATISTICAL_DESIGN_OBJECTIVE (STAT_DESIGN_INDEX)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE TABLE STAT_DESIGN_ONLINE_REL
(
  SOURCE_CITATION_ID  NUMBER,
  STAT_DESIGN_INDEX   NUMBER                    NOT NULL,
  DESIGN_PK           NUMBER                    NOT NULL,
  CONSTRAINT STAT_DESIGN_O_REL_PK
 PRIMARY KEY
 (DESIGN_PK),
  CONSTRAINT STAT_DESIGN_O_REL_R01 
 FOREIGN KEY (METHOD_ID) 
 REFERENCES METHOD_ONLINE (METHOD_ID),
  CONSTRAINT STAT_DESIGN_O_REL_R02 
 FOREIGN KEY (STAT_DESIGN_INDEX) 
 REFERENCES STATISTICAL_DESIGN_OBJECTIVE (STAT_DESIGN_INDEX)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE TABLE STAT_DESIGN_STG_REL
(
  SOURCE_CITATION_ID  NUMBER,
  STAT_DESIGN_INDEX   NUMBER                    NOT NULL,
  DESIGN_PK           NUMBER                    NOT NULL,
  CONSTRAINT STAT_DESIGN_S_REL_PK
 PRIMARY KEY
 (DESIGN_PK),
  CONSTRAINT STAT_DESIGN_S_REL_R01 
 FOREIGN KEY (METHOD_ID) 
 REFERENCES METHOD_STG (METHOD_ID),
  CONSTRAINT STAT_DESIGN_S_REL_R02 
 FOREIGN KEY (STAT_DESIGN_INDEX) 
 REFERENCES STATISTICAL_DESIGN_OBJECTIVE (STAT_DESIGN_INDEX)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE TABLE STAT_MEDIA_REL
(
  SOURCE_CITATION_ID  NUMBER                    NOT NULL,
  STAT_MEDIA_INDEX    NUMBER                    NOT NULL,
  MEDIA_PK            NUMBER                    NOT NULL,
  CONSTRAINT STAT_MEDIA_REL_PK
 PRIMARY KEY
 (MEDIA_PK),
  CONSTRAINT STAT_MEDIA_REL_R01 
 FOREIGN KEY (METHOD_ID) 
 REFERENCES METHOD (METHOD_ID),
  CONSTRAINT STAT_MEDIA_REL_R02 
 FOREIGN KEY (MEDIA_PK) 
 REFERENCES MEDIA_NAME_DOM (MEDIA_ID)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE TABLE STAT_MEDIA_ONLINE_REL
(
  SOURCE_CITATION_ID  NUMBER                    NOT NULL,
  STAT_MEDIA_INDEX    NUMBER                    NOT NULL,
  MEDIA_PK            NUMBER                    NOT NULL,
  CONSTRAINT STAT_MEDIA_O_REL_PK
 PRIMARY KEY
 (MEDIA_PK),
  CONSTRAINT STAT_MEDIA_O_REL_R01 
 FOREIGN KEY (METHOD_ID) 
 REFERENCES METHOD_ONLINE (METHOD_ID),
  CONSTRAINT STAT_MEDIA_REL_O_R02 
 FOREIGN KEY (MEDIA_PK) 
 REFERENCES MEDIA_NAME_DOM (MEDIA_ID)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE TABLE STAT_MEDIA_STG_REL
(
  SOURCE_CITATION_ID  NUMBER                    NOT NULL,
  STAT_MEDIA_INDEX    NUMBER                    NOT NULL,
  MEDIA_PK            NUMBER                    NOT NULL,
  CONSTRAINT STAT_MEDIA_S_REL_PK
 PRIMARY KEY
 (MEDIA_PK),
  CONSTRAINT STAT_MEDIA_S_REL_R01 
 FOREIGN KEY (METHOD_ID) 
 REFERENCES METHOD_STG (METHOD_ID),
  CONSTRAINT STAT_MEDIA_REL_S_R02 
 FOREIGN KEY (MEDIA_PK) 
 REFERENCES MEDIA_NAME_DOM (MEDIA_ID)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE TABLE STAT_TOPICS_REL
(
  SOURCE_CITATION_ID  NUMBER,
  STAT_TOPICS_INDEX   NUMBER,
  TOPICS_PK           NUMBER                    NOT NULL,
  CONSTRAINT STAT_TOPICS_REL_PK
 PRIMARY KEY
 (TOPICS_PK),
  CONSTRAINT STAT_TOPICS_REL_R01 
 FOREIGN KEY (METHOD_ID) 
 REFERENCES METHOD (METHOD_ID),
  CONSTRAINT STAT_TOPICS_REL_R02 
 FOREIGN KEY (STAT_TOPICS_INDEX) 
 REFERENCES STATISTICAL_TOPICS (STAT_TOPIC_INDEX)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE TABLE STAT_TOPICS_ONLINE_REL
(
  SOURCE_CITATION_ID  NUMBER,
  STAT_TOPICS_INDEX   NUMBER,
  TOPICS_PK           NUMBER                    NOT NULL,
  CONSTRAINT STAT_TOPICS_O_REL_PK
 PRIMARY KEY
 (TOPICS_PK),
  CONSTRAINT STAT_TOPICS_O_REL_R01 
 FOREIGN KEY (METHOD_ID) 
 REFERENCES METHOD_ONLINE (METHOD_ID),
  CONSTRAINT STAT_TOPICS_REL_R02 
 FOREIGN KEY (STAT_TOPICS_INDEX) 
 REFERENCES STATISTICAL_TOPICS (STAT_TOPIC_INDEX)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE TABLE STAT_TOPICS_STG_REL
(
  SOURCE_CITATION_ID  NUMBER,
  STAT_TOPICS_INDEX   NUMBER,
  TOPICS_PK           NUMBER                    NOT NULL,
  CONSTRAINT STAT_TOPICS_REL_S_PK
 PRIMARY KEY
 (TOPICS_PK),
  CONSTRAINT STAT_TOPICS_REL_S_R01 
 FOREIGN KEY (METHOD_ID) 
 REFERENCES METHOD_STG (METHOD_ID),
  CONSTRAINT STAT_TOPICS_REL_S_R02 
 FOREIGN KEY (STAT_TOPICS_INDEX) 
 REFERENCES STATISTICAL_TOPICS (STAT_TOPIC_INDEX)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;