# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-27 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_method_managed'),
    ]

    operations = [
        migrations.RunSQL(
            'ALTER TABLE "METHOD" ADD "FIELD_OR_LAB" VARCHAR2(5 CHAR) NULL;',
            reverse_sql='ALTER TABLE "METHOD" DROP COLUMN "FIELD_OR_LAB";',
            state_operations=[
                migrations.AddField(
                    model_name='method',
                    name='field_or_lab',
                    field=models.CharField(blank=True, choices=[(None, 'N/A'), ('Field', 'Field'), ('Lab', 'Lab')], help_text='If the method defines field or lab processing ("pick") of invert samples or field or lab ID of fish species, use this field.', max_length=5, null=True, verbose_name='Field or Lab'),
                )
            ]
        ),
        migrations.RunSQL(
            'ALTER TABLE "METHOD" ADD "FIELD_PRESERVATIVE" VARCHAR2(16 CHAR) NULL;',
            reverse_sql='ALTER TABLE "METHOD" DROP COLUMN "FIELD_PRESERVATIVE";',
            state_operations=[
                migrations.AddField(
                    model_name='method',
                    name='field_preservative',
                    field=models.CharField(blank=True, choices=[(None, 'N/A'), ('Yes', 'Yes'), ('No', 'No'), ('Not Specified', 'Not Specified')], max_length=16, null=True, verbose_name='Field preservative'),
                )
            ]
        ),
        migrations.RunSQL(
            'ALTER TABLE "METHOD" ADD "HABITATS_SAMPLED" VARCHAR2(240 CHAR) NULL;',
            reverse_sql='ALTER TABLE "METHOD" DROP COLUMN "HABITATS_SAMPLED";',
            state_operations=[
                migrations.AddField(
                    model_name='method',
                    name='habitats_sampled',
                    field=models.CharField(blank=True, help_text='Ex: "riffle. in absence of riffle, sample overhanging veg. or in-stream snags"', max_length=240, null=True, verbose_name='Habitat(s) sampled'),
                )
            ]
        ),
        migrations.RunSQL(
            'ALTER TABLE "METHOD" ADD "INDEX_PERIOD" VARCHAR2(240 CHAR) NULL;',
            reverse_sql='ALTER TABLE "METHOD" DROP COLUMN "INDEX_PERIOD";',
            state_operations=[
                migrations.AddField(
                    model_name='method',
                    name='index_period',
                    field=models.CharField(blank=True, help_text='If the method defines a sampling period, put that information here. Ex: "July 15 - Sept. 15"', max_length=240, null=True, verbose_name='Index period'),
                )
            ]
        ),
        migrations.RunSQL(
            'ALTER TABLE "METHOD" ADD "LABORATORY_SUBSAMPLE" VARCHAR2(240 CHAR) NULL;',
            reverse_sql='ALTER TABLE "METHOD" DROP COLUMN "LABORATORY_SUBSAMPLE";',
            state_operations=[
                migrations.AddField(
                    model_name='method',
                    name='laboratory_subsample',
                    field=models.CharField(blank=True, help_text='Ex: "Yes"; "200 or 300 organisms +/- 20%"', max_length=240, null=True, verbose_name='Laboratory subsample?'),
                )
            ]
        ),
        migrations.RunSQL(
            'ALTER TABLE "METHOD" ADD "LARGE_RARE_PICK" VARCHAR2(16 CHAR) NULL;',
            reverse_sql='ALTER TABLE "METHOD" DROP COLUMN "LARGE_RARE_PICK";',
            state_operations=[
                migrations.AddField(
                    model_name='method',
                    name='large_rare_pick',
                    field=models.CharField(blank=True, choices=[(None, 'N/A'), ('Yes', 'Yes'), ('No', 'No'), ('Not Specified', 'Not Specified')], help_text='Choices: Yes. No. Not specified. N/A.', max_length=16, null=True, verbose_name='Large/rare pick?'),
                )
            ]
        ),
        migrations.RunSQL(
            'ALTER TABLE "METHOD" ADD "MESH_SIZE" VARCHAR2(50 CHAR) NULL;',
            reverse_sql='ALTER TABLE "METHOD" DROP COLUMN "MESH_SIZE";',
            state_operations=[
                migrations.AddField(
                    model_name='method',
                    name='mesh_size',
                    field=models.CharField(blank=True, help_text='Can apply to invert nets as well as fish dipnets. If the method defines a mesh size, list it here. Include units. Ex: "595 um"', max_length=50, null=True, verbose_name='Mesh size'),
                )
            ]
        ),
        migrations.RunSQL(
            'ALTER TABLE "METHOD" ADD "NUM_SUBSAMPLES_COMPOSITED" VARCHAR2(50 CHAR) NULL;',
            reverse_sql='ALTER TABLE "METHOD" DROP COLUMN "NUM_SUBSAMPLES_COMPOSITED";',
            state_operations=[
                migrations.AddField(
                    model_name='method',
                    name='num_subsamples_composited',
                    field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Number of individual subsamples composited'),
                )
            ]
        ),
        migrations.RunSQL(
            'ALTER TABLE "METHOD" ADD "SAMPLING_REACH_LENGTH" VARCHAR2(240 CHAR) NULL;',
            reverse_sql='ALTER TABLE "METHOD" DROP COLUMN "SAMPLING_REACH_LENGTH";',
            state_operations=[
                migrations.AddField(
                    model_name='method',
                    name='sampling_reach_length',
                    field=models.CharField(blank=True, help_text='Ex: "minimum 100 m"; "20x channel width (may be extended to capture two riffle-run or glide-pool sequences)"', max_length=240, null=True, verbose_name='Sampling reach length'),
                )
            ]
        ),
        migrations.RunSQL(
            'ALTER TABLE "METHOD" ADD "TARGET_NUM_ORGANISMS" VARCHAR2(240 CHAR) NULL;',
            reverse_sql='ALTER TABLE "METHOD" DROP COLUMN "TARGET_NUM_ORGANISMS";',
            state_operations=[
                migrations.AddField(
                    model_name='method',
                    name='target_num_organisms',
                    field=models.CharField(blank=True, help_text='Ex: "At least 200; extend sampling past 60 min to achieve if necessary"', max_length=240, null=True, verbose_name='Target number of organisms'),
                )
            ]
        ),
        migrations.RunSQL(
            'ALTER TABLE "METHOD" ADD "TAXA_INCLUDED" VARCHAR2(240 CHAR) NULL;',
            reverse_sql='ALTER TABLE "METHOD" DROP COLUMN "TAXA_INCLUDED";',
            state_operations=[
                migrations.AddField(
                    model_name='method',
                    name='taxa_included',
                    field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Taxa included'),
                )
            ]
        ),
        migrations.RunSQL(
            'ALTER TABLE "METHOD" ADD "TOTAL_SAMPLING_AREA" VARCHAR2(240 CHAR) NULL;',
            reverse_sql='ALTER TABLE "METHOD" DROP COLUMN "TOTAL_SAMPLING_AREA";',
            state_operations=[
                migrations.AddField(
                    model_name='method',
                    name='total_sampling_area',
                    field=models.CharField(blank=True, help_text='Ex: "All targeted habitats within reach"', max_length=240, null=True, verbose_name='Total sampling area'),
                )
            ]
        ),
        migrations.RunSQL(
            'ALTER TABLE "METHOD_ONLINE" ADD "FIELD_OR_LAB" VARCHAR2(5 CHAR) NULL;',
            reverse_sql='ALTER TABLE "METHOD_ONLINE" DROP COLUMN "FIELD_OR_LAB";',
            state_operations=[
                migrations.AddField(
                    model_name='methodonline',
                    name='field_or_lab',
                    field=models.CharField(blank=True, choices=[(None, 'N/A'), ('Field', 'Field'), ('Lab', 'Lab')], help_text='If the method defines field or lab processing ("pick") of invert samples or field or lab ID of fish species, use this field.', max_length=5, null=True, verbose_name='Field or Lab'),
                )
            ]
        ),
        migrations.RunSQL(
            'ALTER TABLE "METHOD_ONLINE" ADD "FIELD_PRESERVATIVE" VARCHAR2(16 CHAR) NULL;',
            reverse_sql='ALTER TABLE "METHOD_ONLINE" DROP COLUMN "FIELD_PRESERVATIVE";',
            state_operations=[
                migrations.AddField(
                    model_name='methodonline',
                    name='field_preservative',
                    field=models.CharField(blank=True, choices=[(None, 'N/A'), ('Yes', 'Yes'), ('No', 'No'), ('Not Specified', 'Not Specified')], max_length=16, null=True, verbose_name='Field preservative'),
                )
            ]
        ),
        migrations.RunSQL(
            'ALTER TABLE "METHOD_ONLINE" ADD "HABITATS_SAMPLED" VARCHAR2(240 CHAR) NULL;',
            reverse_sql='ALTER TABLE "METHOD_ONLINE" DROP COLUMN "HABITATS_SAMPLED";',
            state_operations=[
                migrations.AddField(
                    model_name='methodonline',
                    name='habitats_sampled',
                    field=models.CharField(blank=True, help_text='Ex: "riffle. in absence of riffle, sample overhanging veg. or in-stream snags"', max_length=240, null=True, verbose_name='Habitat(s) sampled'),
                )
            ]
        ),
        migrations.RunSQL(
            'ALTER TABLE "METHOD_ONLINE" ADD "INDEX_PERIOD" VARCHAR2(240 CHAR) NULL;',
            reverse_sql='ALTER TABLE "METHOD_ONLINE" DROP COLUMN "INDEX_PERIOD";',
            state_operations=[
                migrations.AddField(
                    model_name='methodonline',
                    name='index_period',
                    field=models.CharField(blank=True, help_text='If the method defines a sampling period, put that information here. Ex: "July 15 - Sept. 15"', max_length=240, null=True, verbose_name='Index period'),
                )
            ]
        ),
        migrations.RunSQL(
            'ALTER TABLE "METHOD_ONLINE" ADD "LABORATORY_SUBSAMPLE" VARCHAR2(240 CHAR) NULL;',
            reverse_sql='ALTER TABLE "METHOD_ONLINE" DROP COLUMN "LABORATORY_SUBSAMPLE";',
            state_operations=[
                migrations.AddField(
                    model_name='methodonline',
                    name='laboratory_subsample',
                    field=models.CharField(blank=True, help_text='Ex: "Yes"; "200 or 300 organisms +/- 20%"', max_length=240, null=True, verbose_name='Laboratory subsample?'),
                )
            ]
        ),
        migrations.RunSQL(
            'ALTER TABLE "METHOD_ONLINE" ADD "LARGE_RARE_PICK" VARCHAR2(16 CHAR) NULL;',
            reverse_sql='ALTER TABLE "METHOD_ONLINE" DROP COLUMN "LARGE_RARE_PICK";',
            state_operations=[
                migrations.AddField(
                    model_name='methodonline',
                    name='large_rare_pick',
                    field=models.CharField(blank=True, choices=[(None, 'N/A'), ('Yes', 'Yes'), ('No', 'No'), ('Not Specified', 'Not Specified')], help_text='Choices: Yes. No. Not specified. N/A.', max_length=16, null=True, verbose_name='Large/rare pick?'),
                )
            ]
        ),
        migrations.RunSQL(
            'ALTER TABLE "METHOD_ONLINE" ADD "MESH_SIZE" VARCHAR2(50 CHAR) NULL;',
            reverse_sql='ALTER TABLE "METHOD_ONLINE" DROP COLUMN "MESH_SIZE";',
            state_operations=[
                migrations.AddField(
                    model_name='methodonline',
                    name='mesh_size',
                    field=models.CharField(blank=True, help_text='Can apply to invert nets as well as fish dipnets. If the method defines a mesh size, list it here. Include units. Ex: "595 um"', max_length=50, null=True, verbose_name='Mesh size'),
                )
            ]
        ),
        migrations.RunSQL(
            'ALTER TABLE "METHOD_ONLINE" ADD "NUM_SUBSAMPLES_COMPOSITED" VARCHAR2(50 CHAR) NULL;',
            reverse_sql='ALTER TABLE "METHOD_ONLINE" DROP COLUMN "NUM_SUBSAMPLES_COMPOSITED";',
            state_operations=[
                migrations.AddField(
                    model_name='methodonline',
                    name='num_subsamples_composited',
                    field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Number of individual subsamples composited'),
                )
            ]
        ),
        migrations.RunSQL(
            'ALTER TABLE "METHOD_ONLINE" ADD "SAMPLING_REACH_LENGTH" VARCHAR2(240 CHAR) NULL;',
            reverse_sql='ALTER TABLE "METHOD_ONLINE" DROP COLUMN "SAMPLING_REACH_LENGTH";',
            state_operations=[
                migrations.AddField(
                    model_name='methodonline',
                    name='sampling_reach_length',
                    field=models.CharField(blank=True, help_text='Ex: "minimum 100 m"; "20x channel width (may be extended to capture two riffle-run or glide-pool sequences)"', max_length=240, null=True, verbose_name='Sampling reach length'),
                )
            ]
        ),
        migrations.RunSQL(
            'ALTER TABLE "METHOD_ONLINE" ADD "TARGET_NUM_ORGANISMS" VARCHAR2(240 CHAR) NULL;',
            reverse_sql='ALTER TABLE "METHOD_ONLINE" DROP COLUMN "TARGET_NUM_ORGANISMS";',
            state_operations=[
                migrations.AddField(
                    model_name='methodonline',
                    name='target_num_organisms',
                    field=models.CharField(blank=True, help_text='Ex: "At least 200; extend sampling past 60 min to achieve if necessary"', max_length=240, null=True, verbose_name='Target number of organisms'),
                )
            ]
        ),
        migrations.RunSQL(
            'ALTER TABLE "METHOD_ONLINE" ADD "TAXA_INCLUDED" VARCHAR2(240 CHAR) NULL;',
            reverse_sql='ALTER TABLE "METHOD_ONLINE" DROP COLUMN "TAXA_INCLUDED";',
            state_operations=[
                migrations.AddField(
                    model_name='methodonline',
                    name='taxa_included',
                    field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Taxa included'),
                )
            ]
        ),
        migrations.RunSQL(
            'ALTER TABLE "METHOD_ONLINE" ADD "TOTAL_SAMPLING_AREA" VARCHAR2(240 CHAR) NULL;',
            reverse_sql='ALTER TABLE "METHOD_ONLINE" DROP COLUMN "TOTAL_SAMPLING_AREA";',
            state_operations=[
                migrations.AddField(
                    model_name='methodonline',
                    name='total_sampling_area',
                    field=models.CharField(blank=True, help_text='Ex: "All targeted habitats within reach"', max_length=240, null=True, verbose_name='Total sampling area'),
                )
            ]
        ),
        migrations.RunSQL(
            'ALTER TABLE "METHOD_STG" ADD "FIELD_OR_LAB" VARCHAR2(5 CHAR) NULL;',
            reverse_sql='ALTER TABLE "METHOD_STG" DROP COLUMN "FIELD_OR_LAB";',
            state_operations=[
                migrations.AddField(
                    model_name='methodstg',
                    name='field_or_lab',
                    field=models.CharField(blank=True, choices=[(None, 'N/A'), ('Field', 'Field'), ('Lab', 'Lab')], help_text='If the method defines field or lab processing ("pick") of invert samples or field or lab ID of fish species, use this field.', max_length=5, null=True, verbose_name='Field or Lab'),
                )
            ]
        ),
        migrations.RunSQL(
            'ALTER TABLE "METHOD_STG" ADD "FIELD_PRESERVATIVE" VARCHAR2(16 CHAR) NULL;',
            reverse_sql='ALTER TABLE "METHOD_STG" DROP COLUMN "FIELD_PRESERVATIVE";',
            state_operations=[
                migrations.AddField(
                    model_name='methodstg',
                    name='field_preservative',
                    field=models.CharField(blank=True, choices=[(None, 'N/A'), ('Yes', 'Yes'), ('No', 'No'), ('Not Specified', 'Not Specified')], max_length=16, null=True, verbose_name='Field preservative'),
                )
            ]
        ),
        migrations.RunSQL(
            'ALTER TABLE "METHOD_STG" ADD "HABITATS_SAMPLED" VARCHAR2(240 CHAR) NULL;',
            reverse_sql='ALTER TABLE "METHOD_STG" DROP COLUMN "HABITATS_SAMPLED";',
            state_operations=[
                migrations.AddField(
                    model_name='methodstg',
                    name='habitats_sampled',
                    field=models.CharField(blank=True, help_text='Ex: "riffle. in absence of riffle, sample overhanging veg. or in-stream snags"', max_length=240, null=True, verbose_name='Habitat(s) sampled'),
                )
            ]
        ),
        migrations.RunSQL(
            'ALTER TABLE "METHOD_STG" ADD "INDEX_PERIOD" VARCHAR2(240 CHAR) NULL;',
            reverse_sql='ALTER TABLE "METHOD_STG" DROP COLUMN "INDEX_PERIOD";',
            state_operations=[
                migrations.AddField(
                    model_name='methodstg',
                    name='index_period',
                    field=models.CharField(blank=True, help_text='If the method defines a sampling period, put that information here. Ex: "July 15 - Sept. 15"', max_length=240, null=True, verbose_name='Index period'),
                )
            ]
        ),
        migrations.RunSQL(
            'ALTER TABLE "METHOD_STG" ADD "LABORATORY_SUBSAMPLE" VARCHAR2(240 CHAR) NULL;',
            reverse_sql='ALTER TABLE "METHOD_STG" DROP COLUMN "LABORATORY_SUBSAMPLE";',
            state_operations=[
                migrations.AddField(
                    model_name='methodstg',
                    name='laboratory_subsample',
                    field=models.CharField(blank=True, help_text='Ex: "Yes"; "200 or 300 organisms +/- 20%"', max_length=240, null=True, verbose_name='Laboratory subsample?'),
                )
            ]
        ),
        migrations.RunSQL(
            'ALTER TABLE "METHOD_STG" ADD "LARGE_RARE_PICK" VARCHAR2(16 CHAR) NULL;',
            reverse_sql='ALTER TABLE "METHOD_STG" DROP COLUMN "LARGE_RARE_PICK";',
            state_operations=[
                migrations.AddField(
                    model_name='methodstg',
                    name='large_rare_pick',
                    field=models.CharField(blank=True, choices=[(None, 'N/A'), ('Yes', 'Yes'), ('No', 'No'), ('Not Specified', 'Not Specified')], help_text='Choices: Yes. No. Not specified. N/A.', max_length=16, null=True, verbose_name='Large/rare pick?'),
                )
            ]
        ),
        migrations.RunSQL(
            'ALTER TABLE "METHOD_STG" ADD "MESH_SIZE" VARCHAR2(50 CHAR) NULL;',
            reverse_sql='ALTER TABLE "METHOD_STG" DROP COLUMN "MESH_SIZE";',
            state_operations=[
                migrations.AddField(
                    model_name='methodstg',
                    name='mesh_size',
                    field=models.CharField(blank=True, help_text='Can apply to invert nets as well as fish dipnets. If the method defines a mesh size, list it here. Include units. Ex: "595 um"', max_length=50, null=True, verbose_name='Mesh size'),
                )
            ]
        ),
        migrations.RunSQL(
            'ALTER TABLE "METHOD_STG" ADD "NUM_SUBSAMPLES_COMPOSITED" VARCHAR2(50 CHAR) NULL;',
            reverse_sql='ALTER TABLE "METHOD_STG" DROP COLUMN "NUM_SUBSAMPLES_COMPOSITED";',
            state_operations=[
                migrations.AddField(
                    model_name='methodstg',
                    name='num_subsamples_composited',
                    field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Number of individual subsamples composited'),
                )
            ]
        ),
        migrations.RunSQL(
            'ALTER TABLE "METHOD_STG" ADD "SAMPLING_REACH_LENGTH" VARCHAR2(240 CHAR) NULL;',
            reverse_sql='ALTER TABLE "METHOD_STG" DROP COLUMN "SAMPLING_REACH_LENGTH";',
            state_operations=[
                migrations.AddField(
                    model_name='methodstg',
                    name='sampling_reach_length',
                    field=models.CharField(blank=True, help_text='Ex: "minimum 100 m"; "20x channel width (may be extended to capture two riffle-run or glide-pool sequences)"', max_length=240, null=True, verbose_name='Sampling reach length'),
                )
            ]
        ),
        migrations.RunSQL(
            'ALTER TABLE "METHOD_STG" ADD "TARGET_NUM_ORGANISMS" VARCHAR2(240 CHAR) NULL;',
            reverse_sql='ALTER TABLE "METHOD_STG" DROP COLUMN "TARGET_NUM_ORGANISMS";',
            state_operations=[
                migrations.AddField(
                    model_name='methodstg',
                    name='target_num_organisms',
                    field=models.CharField(blank=True, help_text='Ex: "At least 200; extend sampling past 60 min to achieve if necessary"', max_length=240, null=True, verbose_name='Target number of organisms'),
                )
            ]
        ),
        migrations.RunSQL(
            'ALTER TABLE "METHOD_STG" ADD "TAXA_INCLUDED" VARCHAR2(240 CHAR) NULL;',
            reverse_sql='ALTER TABLE "METHOD_STG" DROP COLUMN "TAXA_INCLUDED";',
            state_operations=[
                migrations.AddField(
                    model_name='methodstg',
                    name='taxa_included',
                    field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Taxa included'),
                )
            ]
        ),
        migrations.RunSQL(
            'ALTER TABLE "METHOD_STG" ADD "TOTAL_SAMPLING_AREA" VARCHAR2(240 CHAR) NULL;',
            reverse_sql='ALTER TABLE "METHOD_STG" DROP COLUMN "TOTAL_SAMPLING_AREA";',
            state_operations=[
                migrations.AddField(
                    model_name='methodstg',
                    name='total_sampling_area',
                    field=models.CharField(blank=True, help_text='Ex: "All targeted habitats within reach"', max_length=240, null=True, verbose_name='Total sampling area'),
                )
            ]
        ),
    ]
