# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-26 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_add_biological_fields'),
    ]

    operations = [
        migrations.RunSQL(
            'ALTER TABLE "METHOD" MODIFY "SOURCE_METHOD_IDENTIFIER" VARCHAR2(45 CHAR);',
            state_operations=[
                migrations.AlterField(
                    model_name='method',
                    name='source_method_identifier',
                    field=models.CharField(help_text='The method number / identifier can be numerical (e.g., 375.4), numerical w/text (e.g., 4500-SO4 C) or all text (e.g., Simplate). NOTE: If your method number ends in a "0" (e.g., 300.0), please contact the NEMI manager (entries ending in "0" are automatically truncated in Excel, and must be fixed by the NEMI manager).\nWhatever the format, you must choose a unique method number for your method. Also, keep things specific; do not use "Not Applicable," "Color Method" or something of that nature. If your method does not have a unique identifier, you must create one -- consider using a document number (e.g., EPA-XX-X-XXXX), product number, etc..\nIF a method has a published method number THEN include it ELSE create one', max_length=45, unique=True, verbose_name='method number/identifier'),
                )
            ]
        ),
        migrations.RunSQL(
            'ALTER TABLE "METHOD_ONLINE" MODIFY "SOURCE_METHOD_IDENTIFIER" VARCHAR2(45 CHAR);',
            state_operations=[
                migrations.AlterField(
                    model_name='methodonline',
                    name='source_method_identifier',
                    field=models.CharField(help_text='The method number / identifier can be numerical (e.g., 375.4), numerical w/text (e.g., 4500-SO4 C) or all text (e.g., Simplate). NOTE: If your method number ends in a "0" (e.g., 300.0), please contact the NEMI manager (entries ending in "0" are automatically truncated in Excel, and must be fixed by the NEMI manager).\nWhatever the format, you must choose a unique method number for your method. Also, keep things specific; do not use "Not Applicable," "Color Method" or something of that nature. If your method does not have a unique identifier, you must create one -- consider using a document number (e.g., EPA-XX-X-XXXX), product number, etc..\nIF a method has a published method number THEN include it ELSE create one', max_length=45, unique=True, verbose_name='method number/identifier'),
                )
            ]
        ),
        migrations.RunSQL(
            'ALTER TABLE "METHOD_STG" MODIFY "SOURCE_METHOD_IDENTIFIER" VARCHAR2(45 CHAR);',
            state_operations=[
                migrations.AlterField(
                    model_name='methodstg',
                    name='source_method_identifier',
                    field=models.CharField(help_text='The method number / identifier can be numerical (e.g., 375.4), numerical w/text (e.g., 4500-SO4 C) or all text (e.g., Simplate). NOTE: If your method number ends in a "0" (e.g., 300.0), please contact the NEMI manager (entries ending in "0" are automatically truncated in Excel, and must be fixed by the NEMI manager).\nWhatever the format, you must choose a unique method number for your method. Also, keep things specific; do not use "Not Applicable," "Color Method" or something of that nature. If your method does not have a unique identifier, you must create one -- consider using a document number (e.g., EPA-XX-X-XXXX), product number, etc..\nIF a method has a published method number THEN include it ELSE create one', max_length=45, unique=True, verbose_name='method number/identifier'),
                )
            ]
        )
    ]
